### ISSUE TITLE
ver: 6.0.2 changelog tag hash and tag message issues.

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#13]
1)  the changelog part doesnt care if all tags are local it still pushed all previous git messages into the tag messages

```log
* global: update deps (the-j0k3r)
* brighten color for tag add/remove btns (the-j0k3r)
* fix tag add/remove button width (the-j0k3r)
* v1.22.127 (silverwind)
* automated regeneration (silverwind)
* brighten .table-list-header-toggle .btn-link (the-j0k3r)
* dont override .bg-blue-light (the-j0k3r)
* brighten suggestion a color (the-j0k3r)
* prevent perfectionist from chaging domain() position. (the-j0k3r)
* style support Mona Lisa searching img (the-j0k3r)
* add support site to gen and regenerate (the-j0k3r)
* global regenerate (the-j0k3r)
* add https://support.github.com/contact (the-j0k3r)
* global: clean (the-j0k3r)
* better fix for .settings-disabled-remove-email trashcan color (the-j0k3r)
* fix .settings-disabled-remove-email trashcan color (the-j0k3r)
* fix another bg-blue-light (the-j0k3r)
* fix .bg-blue-light (the-j0k3r)
* Style inline pending checks donut chart (Brian Surowiec)
* Fix text color of oauth permission level label (Brian Surowiec)
* Add #eaeaea to the generator (Brian Surowiec)
* Keep the border on .blankslate-capped elements (Brian Surowiec)
```

2)  the actual tag commit hash is the previous commit to the actual tag commit in master

**expected:** Essentially the tag needs to include its own commit hash not the previous commit hash for whatever was commited into master.

https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.22.128 tagged at [0af3005](https://github.com/StylishThemes/GitHub-Dark/commit/2d81283971a8eb18035d2ba0de09b99bc498dc46) corresponds to the the previous commit before bump and not tip of master including bump at https://github.com/StylishThemes/GitHub-Dark/commit/2d81283971a8eb18035d2ba0de09b99bc498dc46

for that last problem its also happening in https://github.com/StylishThemes/Wikipedia-Dark/commit/3ed238a0b0362b26474879a285ef6e94ebff752f#comments

## To confirm issue with hashes

see https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.22.109 the hash corresponds to the actual tag of the master commit creating it, not like now the one before.

and see latest GitHub Dark tags and master commit hashes and tag messages are def gone awry

_Originally posted by @the-j0k3r in https://github.com/silverwind/ver/issues/12#issuecomment-547341295_

**Comment by the-j0k3r** [comment]
## tag hash

GitHub tag https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.22.130 with hash [42b2940](https://github.com/StylishThemes/GitHub-Dark/commit/42b2940d906c9f1effbda4bb6c7a7371b22b47b2) belong to previous commit to actual tag.

![Capture](https://user-images.githubusercontent.com/31389848/68013980-9e208e00-fc8e-11e9-9a97-11c2d532d440.PNG)

## changelog doesnt care about local tags and wacks them all in.

```

v1.22.130

@the-j0k3r the-j0k3r tagged this 12 minutes ago · 1 commit to master since this tag

* global: regenerate (the-j0k3r)
* generator: use $background closes #1004 (the-j0k3r)
* fix template edit bg-white re: #1020 (the-j0k3r)
* brighten table-list text color (the-j0k3r)
* fix table bg its not transparent (the-j0k3r)
* Fix user invite drop down hover style (Brian Surowiec)
* prevent select button from losing style on focus (the-j0k3r)
* v1.22.129 (the-j0k3r)
* global: regenerate (the-j0k3r)
* v1.22.128 (the-j0k3r)
```

**Comment by the-j0k3r** [comment]
The changelog option is especially broken on Windows https://github.com/StylishThemes/Wikipedia-Dark/releases/tag/v2.3.20 and https://github.com/StylishThemes/Wikipedia-Dark/releases/tag/v2.3.21

both with ver globally installed in order to be able to use it in this repo with explicit command. 

`ver -p -C patch wikipedia-dark.user.css`

**Comment by the-j0k3r** [comment]
OK at version 4.3.0 the tag on master doesn't coincide with the actual latest commit either see https://github.com/StylishThemes/Feature-Override-Styles/releases/tag/v0.0.1

**Comment by silverwind** [comment]
Changelog including last tag commit is fixed

Regarding mashed messages, I'm not sure. It does look fine on the CLI:

```
Wikipedia-Dark $ git show v2.3.21
tag v2.3.21
Tagger: the-j0k3r <31389848+the-j0k3r@users.noreply.github.com>
Date:   Sun Nov 3 08:22:50 2019 +0000

* apply generic svg bg fix closes #93 (the-j0k3r)
* fix linter (the-j0k3r)
```

Regarding changelog going over multiple tag commits: I think this must be because not all tags exist locally. Are you sure you did `git pull --tags origin master` before bumping?

**Comment by the-j0k3r** [comment]
> Are you sure you did `git pull --tags origin master` before bumping?

More than sure.

**Comment by silverwind** [comment]
Check `git log 'v1.22.138...HEAD' '--pretty=format:* %s (%an)'` the next time it happens. If that shows different output than what was written in the changelog, there's a bug here, otherwise you're missing tags.

**Comment by the-j0k3r** [comment]
> otherwise you're missing tags.

Pretty sure Im not, but will check

**Comment by the-j0k3r** [comment]
```
git orebase
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (23/23), done.

remote: Total 42 (delta 25), reused 35 (delta 19), pack-reused 0
Unpacking objects: 100% (42/42), done.
From https://github.com/StylishThemes/GitHub-Dark
 * branch              master     -> FETCH_HEAD
   bf05f77f..bfd6dd73  master     -> origin/master
First, rewinding head to replay your work on top of it...
Applying: global update deps and switch to versions
Using index info to reconstruct a base tree...
M       package.json
Falling back to patching base and 3-way merge...
Auto-merging package.json
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (2/2), done.
From https://github.com/StylishThemes/GitHub-Dark
 * branch              master     -> FETCH_HEAD
 * [new tag]           v1.22.138  -> v1.22.138
 * [new tag]           v1.22.139  -> v1.22.139
```

My workflow fetches all tags not local, see it pulled missing tags on rebase using my alias.

I then commit my changes and make a release.

```
> grunt patch
build.json not found - using defaults
Running "patch" task

Running "lint" task

Running "exec:eslint" (exec) task

Running "exec:stylelint" (exec) task


Running "usercss" task

Running "string-replace:inline" (string-replace) task

1 files created

Running "wrap:mozrule" (wrap) task
Wrapped 1 files
Running "exec:usercss" (exec) task
GitHub Dark usercss build complete

Running "exec:patch" (exec) task
+ git tag -f -F - v1.22.140
+ git commit -a -F -
>> warning: CRLF will be replaced by LF in github-dark.css.
>> The file will have its original line endings in your working directory
>> warning: CRLF will be replaced by LF in github-dark.user.css.
>> The file will have its original line endings in your working directory
[master 70e9bb14] v1.22.140
 3 files changed, 21 insertions(+), 4 deletions(-)

Done.
```

```
> git log 'v1.22.140...HEAD' '--pretty=format:* %s (%an)'
* v1.22.140 (the-j0k3r)
```

```
> git tpush
Enumerating objects: 27, done.
Counting objects: 100% (27/27), done.
Delta compression using up to 2 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (21/21), 3.94 KiB | 806.00 KiB/s, done.
Total 21 (delta 16), reused 0 (delta 0)
remote: Resolving deltas: 100% (16/16), completed with 6 local objects.
To https://github.com/StylishThemes/GitHub-Dark.git
   bfd6dd73..70e9bb14  master -> master
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 511 bytes | 127.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To https://github.com/StylishThemes/GitHub-Dark.git
 * [new tag]           v1.22.140 -> v1.22.140
```

https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.22.140

still says commit is behind lol but this time the changelog entries are OK version is 7.0.1 I deleted the node_modules and reinstalled

**Comment by silverwind** [comment]
> git log 'v1.22.140...HEAD' '--pretty=format:* %s (%an)'

This is meant to use the previous tag, e.g. `git log 'v1.22.139...HEAD' '--pretty=format:* %s (%an)'`. If you execute it before `versions` ran, it should give you the changelog.

> The hash commit does not work

What do you mean?

**Comment by silverwind** [comment]
> says one commit made since the to master

That seems like a bug. I see the tag is on the previous commit instead of the version commit, will check later.

```
$ git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit -n 15
* ea95954 - (HEAD -> master, origin/master, origin/HEAD) v1.1.5 (2 hours ago) <the-j0k3r>
* d463453 - (tag: v1.1.5) AV cleanup !important and apply fixes (2 hours ago) <the-j0k3r>
* 7c65639 - chore: switch to versions (2 hours ago) <the-j0k3r>
* 1632534 - global: depupdates (3 days ago) <the-j0k3r>

**Comment by the-j0k3r** [comment]
> That seems like a bug.

Thats the hash bug right there.

> I see the tag is on the previous commit instead of the version commit, will check later.

excellent thx.

**Comment by the-j0k3r** [comment]
Actualy GitHub Dark I switched to versions but not on the script area. =) SO the hash may actually be fixed.

**Comment by silverwind** [comment]
Tag placement fixed in 7.0.2:

```
* ba95f78 - (HEAD -> master, tag: 7.0.2, origin/master) 7.0.2 (14 seconds ago) <silverwind>
* 2309168 - commit before tagging - fixes #13 (36 seconds ago) <silverwind>
* fba4ca2 - update install command (3 hours ago) <silverwind>

**Comment by the-j0k3r** [comment]
So... the changelog is also fixed then? :)

**Comment by silverwind** [comment]
The one where it included changes across multiple versions? I'm not aware of a bug there, to my knowledge that was always a case of missing tags. If you still think it's a bug, give me a repo and commit hash where you get wrong changelogs and open a issue with that info.

**Comment by the-j0k3r** [comment]
tag hash behind again here https://github.com/StylishThemes/GitHub-Dark/releases/tag/v1.22.154

**Comment by silverwind** [comment]
No idea, works for me. Try reinstalling `node_modules`.
