### ISSUE TITLE
changelog not adding all entries

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#15]
https://github.com/StylishThemes/GitHub-Blog-Dark/releases/tag/v1.0.3

![Capture](https://user-images.githubusercontent.com/31389848/69357854-225ea380-0c86-11ea-9348-979a9d36c770.PNG)
```
> git log 'v1.0.2...HEAD' '--pretty=format:* %s (%an)'

* v1.0.3 (the-j0k3r)
* style pagination (the-j0k3r)
* cleanup (the-j0k3r)
* image styling cleanup (the-j0k3r)
* fix links and hovers (the-j0k3r)
* style placeholder (the-j0k3r)
* cat imgs styling (the-j0k3r)
* fix hljs addition/deletion syntax bg (the-j0k3r)
* switch to fg var name (the-j0k3r)
* moz-rule use regexp intead (the-j0k3r)

* meta: update deps + add versions + changelog (the-j0k3r)
```
Notice the space between entries in output, the  missing changelog entry is not straight after the preceding entry, could that be reason?

![Capture](https://user-images.githubusercontent.com/31389848/69357517-82087f00-0c85-11ea-8491-b1fa10bb9b00.PNG)

**Comment by silverwind** [comment]
Indeed, somthing is up here, noticed it too at https://github.com/silverwind/cidr-tools/commits/master.

**Comment by the-j0k3r** [comment]
thx
