### ISSUE TITLE
previous tag commits with ver 4.3.0 shouldnt be added to changelog

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#16]
See https://github.com/StylishThemes/Feature-Override-Styles/releases/tag/v0.0.6

the previous tag is included in changelog all tags are local and created with ver 4.3.0

All tags exist and are local since this repo was created. (I did all releases here).

![Capture](https://user-images.githubusercontent.com/31389848/70043333-90796380-15c0-11ea-996b-bd6b62f5219f.PNG)

None the wiser, but already seen this in other repos for same reason.

**Comment by silverwind** [comment]
try pushing another release. pretty sure the issue is that old tag and commit are not on the same hash, so it will magically work on next tag.

**Comment by the-j0k3r** [comment]
probably that hash thing yea.forgot.
