### ISSUE TITLE
[Feature request] git only commit changes done by versions

### ISSUE THREAD

**Issue by Rotzbua** [silverwind/versions#17]
Thanks for this useful tool :)

## Current behavour

If I want to bump the version of my project I use `versions patch`. But it does not only create a commit with increased version, it also commits all changes.

## Expected behavour

It would be usefull if my default only the version changes by this tool are commited.

## Workaround

My current workaround is to temporarly stash changes, bump version and restore stashed changes.

```bash
git stash
versions patch
git stash apply
```

**Comment by silverwind** [comment]
Indeed, the tool does `git commit -a` which picks up all modified files. Should probably omit the `-a` and `git add` the files modified explicitely. Thought I do think that `-a` might be useful in some situations like when `-c` modifies additional files, so I guess it should be made an options. Will have a look later.

**Comment by silverwind** [comment]
Fixed in 8.0.0 which will only `git add` files modified by the program. There is a new `--all` option to restore previous behaviour of adding all modified files.
