### ISSUE TITLE
versions any release with -C  gitlab commit title includes first two lines of changelog

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#19]
https://gitlab.com/RaitaroH/Stylus-DeepDark

I wonder if thats something to be done here. Not to bothered about it =)

![Capture](https://user-images.githubusercontent.com/31389848/75997275-673ddb80-5eff-11ea-9c72-b4f4ff331182.PNG)

**Comment by silverwind** [comment]
You mean it's only rendered like that on gitlab?

**Comment by silverwind** [comment]
Not sure if solvable. Gitlab seems to squash sufficiently short multi-line commit messages into a single line in that summary message.

<img width="164" alt="image" src="https://user-images.githubusercontent.com/115237/76019554-2efbc480-5f22-11ea-87c7-164c2a5fa5f1.png">

Same in commit view:

<img width="119" alt="image" src="https://user-images.githubusercontent.com/115237/76019516-22776c00-5f22-11ea-8f6d-23e1aee1b421.png">

**Comment by the-j0k3r** [comment]
Its well ugly, Thats what it is.

**Comment by silverwind** [comment]
Apparently GitHub does the same in some places:

![image](https://user-images.githubusercontent.com/115237/76705071-a0373680-66dd-11ea-80d2-b5872a2febf4.png)

https://github.com/silverwind/daemonize-process/actions

Still, I don't think this is solvable.

**Comment by the-j0k3r** [comment]
I think maybe using a breaking space instead of non breaking or regular space may do it.

**Comment by silverwind** [comment]
Nothing to do here, the forge systems should be fixed to properly render multi-line text.
