### ISSUE TITLE
version: make a release not just tag

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#21]
is it possible?, seems GH now prefers releases to show in sidebar

**Comment by silverwind** [comment]
That would require tying the module to GitHub (via their API) but I want it to work everywhere where annotated tags are supported, so I have to say no, I don't want that.

**Comment by silverwind** [comment]
I guess one could optionally support creating releases via the GitHub API, but it should not be the default.

**Comment by the-j0k3r** [comment]
Any advances on this? =) thx.

Hope you're doing well these days.

**Comment by the-j0k3r** [comment]
@silverwind pong, =)

**Comment by silverwind** [comment]
Moving to https://github.com/silverwind/versions/issues/24, which I for some reason opened as duplicate :D
