### ISSUE TITLE
versions conks out with meaningless errors when fails on patch/minor/major.

### ISSUE THREAD

**Issue by the-j0k3r** [silverwind/versions#22]
So essentially the issue I was facing after initial commit with manual rev 0.0.0 I was trying to apply a patch revision ontop.

```
$ npm run patch

> dd-wrt-trac-inspired-themes@0.0.1 patch
> versions -p -C patch dd-wrt-trac-inspired-themes.user.styl

Error: No replacement made in dd-wrt-trac-inspired-themes.user.styl
    at updateFile (file:///C:/Users/Joker/github/dd-wrt-trac-inspired-themes/node_modules/versions/bin/versions.js:38:11243)
    at async main (file:///C:/Users/Joker/github/dd-wrt-trac-inspired-themes/node_modules/versions/bin/versions.js:38:13253)
```

As it turns out for some reason the package.json was set to 0.0.1 already but style wasnt and so until I drank a few more shots and coffee I was none the wiser looking at the files, eventually I noticed the issue.

Would be great if instead of what appears to be meaningless errors, something pointed ppl is right direction.

**Comment by silverwind** [comment]
Please provide files/repo to reproduce if this is still an issue.

**Comment by the-j0k3r** [comment]
Information already provided to test

> As it turns out for some reason the package.json was set to 0.0.1 already but style wasnt and so until I drank a few more shots and coffee I was none the wiser looking at the files, eventually I noticed the issue.

so versions should IMO indicate that there is a version mismatch between package.json/style if this is ever a case.

**Comment by silverwind** [comment]
v10 does not read package.json any more, it only reads the git tag now. If it's used nowhere else and the package is not published, I suggest removing `version` from package.json.

**Comment by the-j0k3r** [comment]
right.

**Comment by the-j0k3r** [comment]
> v10 does not read package.json any more, it only reads the git tag now. If it's used nowhere else and the package is not published, I suggest removing `version` from package.json.

This is not good news, if we use versions to manage versions when publishing packages to npm what then?

**Comment by silverwind** [comment]
This is only about reading version. Writing version to files like package.json can of course be done as normal, it just switched the source of truth to the git tag, so that it can work on repos that do not have the version in any of the files.
